version: '3.8'
services:
  buster:
    build:
        context: .
        dockerfile: Dockerfile
    image: qjoly/molecule-os:debian-buster
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    container_name: buster

