name: debian-bullseye

on:
  push:
  workflow_dispatch:
  
env:
  tag: debian-bullseye
  file: debian/bullseye/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: qjoly
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "qjoly/molecule-os:$tag"
          file: "$file"
