name: Dockerhub README

on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  

jobs:
  readme-update:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Dockerhub Readme
      uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: qjoly
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        readme: ./README.md
        repository: "qjoly/molecule-os"
