name: rockylinux-9

on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
env:
  tag: rockylinux-9
  file: rockylinux/9/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: "qjoly/molecule-os:${{ env.tag }}"
          file: ${{ env.file }}
